
name: 书旗小说

on:
  workflow_dispatch:
  schedule:
     - cron: '0 16-23,0-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }} 
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
      - name: '运行 【书旗小说】'
        if: env.SQ_shuqiuserURL
        run: |
          node Task/shuqi.js
