
name: 书旗小说

on:
  workflow_dispatch:
  schedule:
     - cron: '0 16-23,0-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }} # 更多env见脚本
    steps:
      - name: Checkout
        run: |
          git clone -b main https://github.com/zzzoen/Ziye.git ~/Ziye
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        run: |
          cd ~/Ziye
          npm install
      - name: '运行 【书旗小说】'
        if: env.SQ_shuqiuserURL
          cd ~/Ziye
          node Task/shuqi.js
