# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 书旗小说

on:
  workflow_dispatch:
  schedule:
     - cron: '0 16-23,0-14 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        SQ_shuqiuserURL: ${{ secrets.SQ_shuqiuserURL }} # 更多env见脚本
    steps:
      - name: Checkout
        run: |
          git clone -b main https://github.com/zzzoen/Ziye.git ~/Ziye
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Ziye
          npm install
      - name: '运行 【书旗小说】'     
        run: |
          cd ~/Ziye
          node Task/shuqi.js
